services:
  test_postgres:
    image: postgres:17rc1-alpine
    environment:
      POSTGRES_DB: ${TEST_POSTGRES_DB_NAME}
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
    container_name: postgresql-test-container
    ports:
      - "${TEST_POSTGRES_PORT}:5432"
    volumes:
      - postgresql_test_data:/var/lib/postgresql/data
    env_file:
      - ../.env.docker

  test_redis:
    image: redis:latest
    container_name: redis-test-container
    ports:
      - "${TEST_REDIS_PORT}:6379"
    restart: always
    env_file:
      - ../.env.docker

volumes:
  postgresql_test_data: