"""task model creation

Revision ID: f42df3708325
Revises: 
Create Date: 2024-09-17 00:50:27.658991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f42df3708325'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('Description', sa.String(), nullable=False),
    sa.Column('Complexity', sa.Enum('VERY_EASY', 'EASY', 'MODERATE', 'CHALLENGING', 'DIFFICULT', 'VERY_DIFFICULT', name='complexity'), nullable=False),
    sa.Column('Status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', name='status'), nullable=False),
    sa.Column('Created at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('Deadline', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
