"""task/user models creation

Revision ID: 3d37568bbedf
Revises: 
Create Date: 2024-09-17 22:59:12.828871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d37568bbedf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminusers',
    sa.Column('Username', sa.String(length=255), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('Hashed password', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Created at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('Updated at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adminusers')),
    sa.UniqueConstraint('Email', name=op.f('uq_adminusers_Email')),
    sa.UniqueConstraint('Username', name=op.f('uq_adminusers_Username'))
    )
    op.create_index(op.f('ix_adminusers_id'), 'adminusers', ['id'], unique=False)
    op.create_table('employedusers',
    sa.Column('Phone number', sa.String(length=12), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Username', sa.String(length=255), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('Hashed password', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Created at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('Updated at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employedusers')),
    sa.UniqueConstraint('Email', name=op.f('uq_employedusers_Email')),
    sa.UniqueConstraint('Username', name=op.f('uq_employedusers_Username'))
    )
    op.create_index(op.f('ix_employedusers_id'), 'employedusers', ['id'], unique=False)
    op.create_table('unemployedusers',
    sa.Column('LinkedIn', sa.String(), nullable=True),
    sa.Column('Achivements', sa.Text(), nullable=True),
    sa.Column('Phone number', sa.String(length=12), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Username', sa.String(length=255), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('Hashed password', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Created at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('Updated at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unemployedusers')),
    sa.UniqueConstraint('Email', name=op.f('uq_unemployedusers_Email')),
    sa.UniqueConstraint('Username', name=op.f('uq_unemployedusers_Username'))
    )
    op.create_index(op.f('ix_unemployedusers_id'), 'unemployedusers', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('Description', sa.String(), nullable=False),
    sa.Column('Complexity', sa.Enum('VERY_EASY', 'EASY', 'MODERATE', 'CHALLENGING', 'DIFFICULT', 'VERY_DIFFICULT', name='complexity'), nullable=False),
    sa.Column('Status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', name='status'), nullable=False),
    sa.Column('Deadline', sa.DateTime(), nullable=True),
    sa.Column('Employed user', sa.Integer(), nullable=False),
    sa.Column('Unemployed user', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Created at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('Updated at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['Employed user'], ['employedusers.id'], name=op.f('fk_tasks_Employed user_employedusers')),
    sa.ForeignKeyConstraint(['Unemployed user'], ['unemployedusers.id'], name=op.f('fk_tasks_Unemployed user_unemployedusers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_unemployedusers_id'), table_name='unemployedusers')
    op.drop_table('unemployedusers')
    op.drop_index(op.f('ix_employedusers_id'), table_name='employedusers')
    op.drop_table('employedusers')
    op.drop_index(op.f('ix_adminusers_id'), table_name='adminusers')
    op.drop_table('adminusers')
    # ### end Alembic commands ###
