"""'default'

Revision ID: da0642a9f214
Revises: 
Create Date: 2024-10-04 16:35:58.988393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da0642a9f214'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.LargeBinary(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=12), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'EMPLOYED', 'UNEMPLOYED', name='userrole'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('adminusers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_adminusers_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_adminusers'))
    )
    op.create_table('employedusers',
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_employedusers_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_employedusers'))
    )
    op.create_table('unemployedusers',
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('achivements', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_unemployedusers_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_unemployedusers'))
    )
    op.create_table('tasks',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('complexity', sa.Enum('VERY_EASY', 'EASY', 'MODERATE', 'CHALLENGING', 'DIFFICULT', 'VERY_DIFFICULT', name='complexity'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'COMPLETED', name='status'), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('employed_user_id', sa.Integer(), nullable=False),
    sa.Column('unemployed_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employed_user_id'], ['employedusers.user_id'], name=op.f('fk_tasks_employed_user_id_employedusers')),
    sa.ForeignKeyConstraint(['unemployed_user_id'], ['unemployedusers.user_id'], name=op.f('fk_tasks_unemployed_user_id_unemployedusers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('unemployedusers')
    op.drop_table('employedusers')
    op.drop_table('adminusers')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
